name: 'Conditional workflow
on:
  workflow_dispatch:
    inputs:
      scanners:
        description: 'Scan the code'
        required: true
        default: 'none'
jobs:
  params:
    runs-on: ubuntu-latest
    steps:
      - name: 'Language'
        run: echo 'Input parameters: ${{ github.event.inputs.lang }}'

  go_sequence:
    runs-on: ubuntu-latest
    if: github.event.inputs.lang == 'go'
    env:
      GO111MODULE: on
    steps:
      - name: 'Checkout Source'
        uses: actions/checkout@v4

      - name: 'Create reports folder'
        run: mkdir -p reports

      - name: 'Run gosec Security Scanner'
        uses: securego/gosec@master
        with:
          args: -fmt sarif -out reports/gosec.sarif ./...

      #- name: 'Upload gosec report'
      #  run: |
      #    curl -X POST https://*/reports \
      #      -H "Content-Type: application/sarif+json" \
      #      --data-binary @reports/gosec.sarif


